{{- /* OnePasswordItem resources in release namespace. Requires 1Password operator (e.g. onepassword-operator). */}}
{{- /* Do not use "default true" for enabled: in Helm, false is empty so it would be replaced. */}}
{{- if and (ne .Values.enabled false) (ne (toString (.Values.enabled | default "")) "false") .Values.items }}
{{- range .Values.items }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
type: {{ .type | default "Opaque" }}
spec:
  itemPath: {{ .item }}
{{- end }}
{{- end }}
