{{- /* Post-install/upgrade: apply secretAnnotations/secretLabels to Secrets created by 1Password operator (e.g. for kubernetes-replicator). */}}
{{- $itemsWithMeta := list }}
{{- range .Values.items }}
{{- if or .secretAnnotations .secretLabels }}
{{- $itemsWithMeta = append $itemsWithMeta . }}
{{- end }}
{{- end }}
{{- if and (ne .Values.enabled false) (ne (toString (.Values.enabled | default "")) "false") $itemsWithMeta }}
apiVersion: batch/v1
kind: Job
metadata:
  name: onepassworditem-secret-metadata-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: onepassworditem
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 15
  template:
    spec:
      serviceAccountName: onepassworditem-secret-metadata
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: patch
          image: bitnami/kubectl:1.30
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -ec
            - |
              set -e
              NS="{{ .Release.Namespace }}"
              {{- range $itemsWithMeta }}
              SECRET='{{ .name }}'
              for i in $(seq 1 30); do
                if kubectl get secret -n "$NS" "$SECRET" 2>/dev/null; then break; fi
                echo "Waiting for secret $SECRET (attempt $i/30)..."
                sleep 2
              done
              if ! kubectl get secret -n "$NS" "$SECRET" 2>/dev/null; then
                echo "Secret $SECRET not found after 30 attempts"
                exit 1
              fi
              {{- $meta := dict }}
              {{- if .secretAnnotations }}{{ $meta = merge $meta (dict "annotations" .secretAnnotations) }}{{ end }}
              {{- if .secretLabels }}{{ $meta = merge $meta (dict "labels" .secretLabels) }}{{ end }}
              PATCH_B64='{{ dict "metadata" $meta | toJson | b64enc }}'
              PATCH=$(echo "$PATCH_B64" | base64 -d)
              kubectl patch secret -n "$NS" "$SECRET" --type=merge -p "$PATCH"
              echo "Patched secret $SECRET with annotations/labels"
              {{- end }}
              echo "Done."
{{- end }}
