{{- /* RBAC for the post-install hook that applies secretAnnotations/secretLabels to 1Password-created Secrets. */}}
{{- $itemsWithMeta := list }}
{{- range .Values.items }}
{{- if or .secretAnnotations .secretLabels }}
{{- $itemsWithMeta = append $itemsWithMeta . }}
{{- end }}
{{- end }}
{{- if and (ne .Values.enabled false) (ne (toString (.Values.enabled | default "")) "false") $itemsWithMeta }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onepassworditem-secret-metadata
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: onepassworditem
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: onepassworditem-secret-metadata
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: onepassworditem
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      {{- range $itemsWithMeta }}
      - {{ .name | quote }}
      {{- end }}
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: onepassworditem-secret-metadata
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: onepassworditem
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: onepassworditem-secret-metadata
subjects:
  - kind: ServiceAccount
    name: onepassworditem-secret-metadata
    namespace: {{ .Release.Namespace }}
{{- end }}
